
drop Table _stmtfile;

Create  Table _stmtfile(
 MainSup	Char(25),                       
 CardNumber	Char(25),                       
 CreditLimit	Decimal(16,3), 
 AddLine1	VarChar(50), 
 AddLine2	VarChar(50), 
 AddLine3	VarChar(50), 
 AddLine4	VarChar(50), 
 AddLine5	VarChar(50), 
 billdate	date, 
 prduedate	date, 
 OpenBal	decimal(16,3), 
 DueAmount	decimal(16,3), 
 MinDueAmt	decimal(16,3), 
 Postdate	Date, 
 trxndate	Date, 
 trxndetails	Char(54), 
 TrxnCur	Char(3), 
 DecDigits	Smallint,               
 TrxnAmt	Decimal(16,3), 
 Amount	Decimal(16,3), 
 Name	        Char(30), 
 StmtSerno	Integer, 
 MainCardNum	Char(25), 
 PrevSerno	Integer, 
 TrxnSerno	Integer, 
 CurrAlpha	Char(3), 
 TotalDB	decimal(16,3), 
 TotalCR	decimal(16,3), 
 gMessage1	varchar(50), 
 gMessage2	varchar(50), 
 gMessage3	varchar(50), 
 StmtType 	char(1), 
 gMessage4	varchar(50), 
 gMessage5	varchar(50), 
 TotalFees     decimal(16,3), 
 TotCashPur	decimal(16,3), 
 TotalPymts	decimal(16,3), 
 BankAcc 	varchar(30), 
 trxnref	varchar(30),
 zipCode	varchar(30),
 barCode	varchar(30)
 
) ;