-- =============================================================================
-- STAT_BANK_PRODUCT_CONFIG — Bank/product configuration table
-- =============================================================================
-- Replaces the hundreds of hardcoded chkLstProducts.Items.Add() entries
-- in the legacy frmStatementFileExtn.cs.  Adding a new bank now requires
-- only a new INSERT here — no source-code change is needed.
--
-- Schema owner: STMT  (change prefix if your schema differs)
-- Run order:    1. Create sequence  2. Create table  3. INSERT seed rows
-- =============================================================================

-- ── 1. Sequence ───────────────────────────────────────────────────────────────
CREATE SEQUENCE STAT_BPCFG_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- ── 2. Table ──────────────────────────────────────────────────────────────────
CREATE TABLE STAT_BANK_PRODUCT_CONFIG (
    -- Primary key
    ID                        NUMBER(10)       NOT NULL,

    -- Bank identity
    BRANCH_CODE               NUMBER(10)       NOT NULL,
    BANK_NAME                 VARCHAR2(20)     NOT NULL,   -- short code, e.g. "UBA"
    BANK_FULL_NAME            VARCHAR2(200)    NOT NULL,
    CARD_PRODUCT              VARCHAR2(100),               -- Oracle product code

    -- Output format
    OUTPUT_TYPE               NUMBER(2)        NOT NULL,   -- StatementOutputType enum value
    FORMATTER_KEY             VARCHAR2(50)     NOT NULL,   -- e.g. "HTML_UBA"

    -- Processing flags (bitmask of ProcessingMode enum)
    PROCESSING_MODES          NUMBER(12)       DEFAULT 0 NOT NULL,

    -- Card classification
    CARD_TYPE                 NUMBER(2)        DEFAULT 0 NOT NULL,  -- CardType enum
    STATEMENT_TYPE            NUMBER(2)        DEFAULT 0 NOT NULL,  -- StatementType enum

    -- Statement identity suffix
    STATEMENT_TYPE_SUFFIX     VARCHAR2(10)     DEFAULT 'CR' NOT NULL,  -- CR/DB/CP/VIP/…

    -- Oracle query conditions
    REWARD_CONTRACT_COND      VARCHAR2(500),               -- e.g. '''New Reward Contract'''
    INSTALLMENT_CONTRACT_COND VARCHAR2(500),

    -- Flags (0/1)
    APPEND_MODE               NUMBER(1)        DEFAULT 0 NOT NULL,
    USE_CORP_ACCT_NO          NUMBER(1)        DEFAULT 0 NOT NULL,

    -- PDF
    REPORT_TEMPLATE_NAME      VARCHAR2(200),
    PDF_PASSWORD_SCHEME       VARCHAR2(10),                -- 'DOB' | 'CARD4' | NULL

    -- Email / branding
    EMAIL_FROM_ADDRESS        VARCHAR2(200)    DEFAULT 'cardservices@emp-group.com' NOT NULL,
    BANK_WEBSITE_URL          VARCHAR2(500),
    FACEBOOK_URL              VARCHAR2(500),
    LINKEDIN_URL              VARCHAR2(500),
    YOUTUBE_URL               VARCHAR2(500),

    -- Text-label pagination
    MAX_TRANS_PER_PAGE        NUMBER(4)        DEFAULT 20 NOT NULL,
    MAX_TRANS_LAST_PAGE       NUMBER(4)        DEFAULT 27 NOT NULL,

    -- Email delivery
    EMAIL_WAIT_MS             NUMBER(8)        DEFAULT 7000 NOT NULL,

    -- Raw data
    FIELD_SEPARATOR           VARCHAR2(5)      DEFAULT ',' NOT NULL,

    -- Scheduling & UI
    SCHEDULED_DAY             NUMBER(2)        DEFAULT 1  NOT NULL,  -- day-of-month
    DISPLAY_NAME              VARCHAR2(500),               -- legacy ListItem text
    SORT_ORDER                NUMBER(6)        DEFAULT 0  NOT NULL,
    IS_ACTIVE                 NUMBER(1)        DEFAULT 1  NOT NULL,

    -- Audit
    CREATED_AT                TIMESTAMP        DEFAULT SYSTIMESTAMP NOT NULL,
    MODIFIED_AT               TIMESTAMP        DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_STAT_BPCFG PRIMARY KEY (ID),
    CONSTRAINT CK_BPCFG_OUTPUT    CHECK (OUTPUT_TYPE    BETWEEN 0 AND 5),
    CONSTRAINT CK_BPCFG_ACTIVE    CHECK (IS_ACTIVE      IN (0, 1)),
    CONSTRAINT CK_BPCFG_APPEND    CHECK (APPEND_MODE    IN (0, 1)),
    CONSTRAINT CK_BPCFG_CORP      CHECK (USE_CORP_ACCT_NO IN (0, 1)),
    CONSTRAINT CK_BPCFG_SCHED_DAY CHECK (SCHEDULED_DAY BETWEEN 1 AND 31)
);

-- Indexes for common lookups
CREATE INDEX IDX_BPCFG_BRANCH    ON STAT_BANK_PRODUCT_CONFIG (BRANCH_CODE);
CREATE INDEX IDX_BPCFG_ACTIVE    ON STAT_BANK_PRODUCT_CONFIG (IS_ACTIVE, SORT_ORDER);
CREATE INDEX IDX_BPCFG_FORMATTER ON STAT_BANK_PRODUCT_CONFIG (FORMATTER_KEY);

-- Auto-update MODIFIED_AT on every UPDATE
CREATE OR REPLACE TRIGGER TRG_BPCFG_MOD_AT
BEFORE UPDATE ON STAT_BANK_PRODUCT_CONFIG
FOR EACH ROW
BEGIN
    :NEW.MODIFIED_AT := SYSTIMESTAMP;
END;
/

-- ── 3. Seed data ──────────────────────────────────────────────────────────────
-- Migrated from frmStatementFileExtn.cs.
-- OUTPUT_TYPE values: 0=Html, 1=RawData, 2=TextLabel, 3=Text, 4=Xml, 5=Pdf
-- PROCESSING_MODES values: bitmask of ProcessingMode flags
--   Standard=0, Reward=1, Corporate=2, Supplementary=4, Vip=8, Installment=16,
--   ExternalId=32, WithOverdueDays=64, ExcludeVisa=128, SortCardPriority=256,
--   Omr=512, PasswordProtectedPdf=1024, FixArabicAddress=2048, DeleteOnHold=4096,
--   Prepaid=8192, ExcelExport=16384, MergeMarkUpFees=32768, RemoveMarkupFee=65536,
--   FixAddress=131072, FixArabicAddressLang=262144, PasNoAndBirthYear=524288,
--   ClientBank=1048576

-- ── HTML formatters ────────────────────────────────────────────────────────────

-- UBA – United Bank for Africa (branch 29)
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 29, 'UBA', 'United Bank for Africa Plc Nigeria', 'UBACR', 0, 'HTML_UBA', 0, 0, 0, 'CR', NULL, 'cardservices@emp-group.com', 1, '29) UBA United Bank for Africa Plc Nigeria >> Credit Emails 1/m', 10, 1);

-- ABP – Access Bank (branch 16) Credit HTML
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 16, 'ABP', 'Access Bank Plc', 'ABPCR', 0, 'HTML_ABP', 0, 0, 0, 'CR', NULL, 'cardservices@emp-group.com', 1, '[16] ABP Access Bank Plc >> Credit Emails 1/m', 20, 1);

-- ABP – Access Bank (branch 16) Supplementary HTML
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 16, 'ABP', 'Access Bank Plc', 'ABPCR_SUP', 0, 'HTML_ABP_SUP', 4, 0, 0, 'CR', NULL, 'cardservices@emp-group.com', 1, '[16] ABP Access Bank Plc >> Corporate Cardholder Emails 1/m', 25, 1);

-- AIBK – Arab International Bank Kuwait (branch 4)
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 4, 'AIBK', 'Arab International Bank Kuwait', 'AIBKCR', 0, 'HTML_AIBK', 32, 0, 0, 'CR', NULL, 'cardservices@emp-group.com', 1, '4) AIBK Arab International Bank Kuwait >> Credit Emails 1/m', 30, 1);

-- ALXB – Alexandria Bank (branch 74 placeholder)
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 74, 'ALXB', 'Alexandria Bank', 'ALXBCR', 0, 'HTML_ALXB', 0, 0, 0, 'CR', NULL, 'cardservices@emp-group.com', 1, '74) ALXB Alexandria Bank >> Credit Emails 1/m', 40, 1);

-- BAI – Banco Angolano de Investimentos (branch 7) Credit
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 7, 'BAI', 'Banco Angolano de Investimentos', 'BAICR', 0, 'HTML_BAI_CREDIT', 0, 0, 0, 'CR', NULL, 'cardservices@emp-group.com', 1, '[7] BAI Products >> Email 1/m', 50, 1);

-- BAI – Prepaid
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 7, 'BAI', 'Banco Angolano de Investimentos', 'BAICP', 0, 'HTML_BAI_PREPAID', 8192, 0, 0, 'CP', NULL, 'cardservices@emp-group.com', 1, '[7] BAI Prepaid >> Email 1/m', 55, 1);

-- BDCA – Banque Du Caire (branch 41)
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 41, 'BDCA', 'Banque Du Caire', 'BDCACR', 0, 'HTML_BDCA', 0, 0, 0, 'CR', NULL, 'cardservices@emp-group.com', 5, '41) BDCA Banque Du Caire >> Credit Emails 5/m', 60, 1);

-- BPC – Banco de Poupanca e Credito (branch 22)
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 22, 'BPC', 'Banco de Poupanca e Credito SARL', 'BPCCR', 0, 'HTML_BPC', 0, 0, 0, 'CR', NULL, 'cardservices@emp-group.com', 16, '[22] BPC BANCO DE POUPANCA E CREDITO, SARL Credit >> Cardholder Email 16/m', 70, 1);

-- BPC – Prepaid
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 22, 'BPC', 'Banco de Poupanca e Credito SARL', 'BPCCP', 0, 'HTML_BPC_PREPAID', 8192, 0, 0, 'CP', NULL, 'cardservices@emp-group.com', 1, '[22] BPC BANCO DE POUPANCA E CREDITO, SARL Debit >> Email 1/m', 75, 1);

-- CMB – Cairo Commercial Bank
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 0, 'CMB', 'Cairo Commercial Bank', 'CMBCR', 0, 'HTML_CMB', 1, 0, 0, 'CR', '''New Reward Contract''', 'cardservices@emp-group.com', 1, 'CMB Cairo Commercial Bank >> Credit Emails with Reward 1/m', 80, 1);

-- DBN – Diamond Bank Nigeria (branch 36) Credit
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 36, 'DBN', 'Diamond Bank Nigeria', 'DBNCR', 0, 'HTML_DBN', 1, 0, 0, 'CR', '''New Reward Contract''', 'cardservices@emp-group.com', 16, '[36] DBN Diamond Bank Nigeria >> Email 16/m', 90, 1);

-- FBP – Fidelity Bank PLC (branch 55)
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 55, 'FBP', 'Fidelity Bank PLC', 'FBPCR', 0, 'HTML_FBP', 0, 0, 0, 'CR', NULL, 'cardservices@emp-group.com', 1, '[55] FBP Fidelity Bank PLC >> Emails 1/m', 100, 1);

-- FBN – First Bank of Nigeria (branch 69) Credit
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 69, 'FBN', 'First Bank of Nigeria', 'FBNCR', 0, 'HTML_FBN', 0, 0, 0, 'CR', NULL, 'cardservices@emp-group.com', 16, '[69] FBN First Bank of Nigeria >> Credit Emails 16/m', 110, 1);

-- FBN – Corporate
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, USE_CORP_ACCT_NO, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 69, 'FBN', 'First Bank of Nigeria', 'FBNCORP', 0, 'HTML_FBN_CORP', 2, 0, 0, 'CORP', NULL, 'cardservices@emp-group.com', 1, 1, '[69] FBN First Bank of Nigeria >> Corporate Cardholder Emails 1/m', 115, 1);

-- FBN – Debit
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 69, 'FBN', 'First Bank of Nigeria', 'FBNDB', 0, 'HTML_FBN_DB', 0, 1, 0, 'DB', NULL, 'cardservices@emp-group.com', 16, '[69] FBN First Bank of Nigeria >> Debit Emails 16/m', 117, 1);

-- FBN – Supplementary
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 69, 'FBN', 'First Bank of Nigeria', 'FBNCR_SUP', 0, 'HTML_FBN_SUP', 4, 0, 0, 'CR', NULL, 'cardservices@emp-group.com', 16, '[69] FBN First Bank of Nigeria >> Supplementary Credit Emails 16/m', 118, 1);

-- GTBK – Guaranty Trust Bank Kenya (branch 98)
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 98, 'GTBK', 'Guaranty Trust Bank Kenya', 'GTBKCR', 0, 'HTML_GTBK', 0, 0, 0, 'CR', NULL, 'cardservices@emp-group.com', 1, '[98] GTBK Guaranty Trust Bank Kenya >> Credit Emails 1/m', 120, 1);

-- GTBN – Guaranty Trust Bank Nigeria (branch 38)
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 38, 'GTBN', 'Guaranty Trust Bank PLC Nigeria', 'GTBNCR', 0, 'HTML_GTBN', 0, 0, 0, 'CR', NULL, 'cardservices@emp-group.com', 16, '[38] GTBN Guaranty Trust Bank PLC Nigeria >> Credit Emails 16/m', 125, 1);

-- GTBU – Guaranty Trust Bank Uganda Prepaid
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 113, 'GTBU', 'Guaranty Trust Bank Uganda', 'GTBUCP', 0, 'HTML_GTBU_PREPAID', 8192, 0, 0, 'CP', NULL, 'cardservices@emp-group.com', 1, '113) GTBU Guaranty Trust Bank Uganda >> Prepaid Emails 1/m', 130, 1);

-- HBLN – Heritage Banking Company (branch 110)
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 110, 'HBLN', 'Heritage Banking Company Nigeria', 'HBLNCR', 0, 'HTML_HBLN', 0, 0, 0, 'CR', NULL, 'cardservices@emp-group.com', 1, '[110] HBLN Heritage Banking Company Nigeria >> Credit Emails 1/m', 135, 1);

-- HBLN – Prepaid
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 110, 'HBLN', 'Heritage Banking Company Nigeria', 'HBLNCP', 0, 'HTML_HBLN_PREPAID', 8192, 0, 0, 'CP', NULL, 'cardservices@emp-group.com', 1, '[110] HBLN Heritage Banking Company Nigeria >> Prepaid Emails 1/m', 137, 1);

-- ICBG – Intercontinental Bank Ghana (branch 50)
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 50, 'ICBG', 'Intercontinental Bank Ghana', 'ICBGCR', 0, 'HTML_ICBG', 0, 0, 0, 'CR', NULL, 'cardservices@emp-group.com', 1, '50) ICBG Intercontinental Bank Ghana Limited Credit >> Emails 1/m', 140, 1);

-- IMB Prepaid
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 0, 'IMB', 'IMB Bank', 'IMBCP', 0, 'HTML_IMB_PREPAID', 8192, 0, 0, 'CP', NULL, 'cardservices@emp-group.com', 1, 'IMB Prepaid >> Email 1/m', 145, 1);

-- NBS – NBS Bank Limited (branch 31)
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 31, 'NBS', 'NBS Bank Limited', 'NBSCR', 0, 'HTML_NBS', 0, 0, 0, 'CR', NULL, 'cardservices@emp-group.com', 16, '[31] NBS NBS Bank Limited >> Email 16/m', 150, 1);

-- SBN – Sterling Bank Nigeria (branch 47)
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 47, 'SBN', 'Sterling Bank Nigeria', 'SBNCR', 0, 'HTML_SBN', 0, 0, 0, 'CR', NULL, 'cardservices@emp-group.com', 1, '[47] SBN Sterling Bank Nigeria >> Default Credit Email 1/m', 160, 1);

-- SBP – Polaris/Skye Bank PLC (branch 58) Credit
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 58, 'SBP', 'Polaris/Skye Bank PLC', 'SBPCR', 0, 'HTML_SBP', 0, 0, 0, 'CR', NULL, 'cardservices@emp-group.com', 1, '[58] SBP SKYE BANK PLC >> Emails 1/m', 170, 1);

-- SBP – Debit
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 58, 'SBP', 'Polaris/Skye Bank PLC', 'SBPDB', 0, 'HTML_SBP_DB', 0, 1, 0, 'DB', NULL, 'cardservices@emp-group.com', 1, 'SBP Polaris/Skye Bank >> Debit Emails 1/m', 173, 1);

-- SBP – Prepaid
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 58, 'SBP', 'Polaris/Skye Bank PLC', 'SBPCP', 0, 'HTML_SBP_PREPAID', 8192, 0, 0, 'CP', NULL, 'cardservices@emp-group.com', 1, '[58] SBP SKYE BANK PLC >> Prepaid VISA Emails 1/m', 175, 1);

-- SIBN – Stanbic IBTC Bank Nigeria (branch 81)
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 81, 'SIBN', 'Stanbic IBTC Bank Nigeria', 'SIBNCR', 0, 'HTML_SIBN', 0, 0, 0, 'CR', NULL, 'cardservices@emp-group.com', 1, '[81] SIBN STANBIC IBTC BANK NIGERIA >> Credit Platinum Emails 1/m', 185, 1);

-- UBAG – UBA Ghana Prepaid (branch 32)
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 32, 'UBAG', 'United Bank for Africa Ghana', 'UBAGCP', 0, 'HTML_UBAG_PREPAID', 8192, 0, 0, 'CP', NULL, 'cardservices@emp-group.com', 1, '[32] UBAG UNITED BANK FOR AFRICA GHANA LIMITED >> Debit Email 1/m', 190, 1);

-- UNBN Credit
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 0, 'UNBN', 'Union Bank Nigeria', 'UNBNCR', 0, 'HTML_UNBN', 0, 0, 0, 'CR', NULL, 'cardservices@emp-group.com', 1, 'UNBN Union Bank Nigeria >> Credit Emails 1/m', 195, 1);

-- WEMA – WEMA Bank PLC Nigeria (branch 87)
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 87, 'WEMA', 'WEMA Bank PLC Nigeria', 'WEMACR', 0, 'HTML_WEMA', 0, 0, 0, 'CR', NULL, 'cardservices@emp-group.com', 15, '[87] WEMA BANK PLC NIGERIA >> Credit Emails 15/m', 200, 1);

-- WEMA – Debit
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 87, 'WEMA', 'WEMA Bank PLC Nigeria', 'WEMADB', 0, 'HTML_WEMA_DB', 0, 1, 0, 'DB', NULL, 'cardservices@emp-group.com', 15, '[87] WEMA BANK PLC NIGERIA >> Debit Emails 15/m', 203, 1);

-- AAIB – Arab African International Bank (branch 6)
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 6, 'AAIB', 'Arab African International Bank', 'AAIBCR', 0, 'HTML_AAIB', 0, 0, 0, 'CR', NULL, 'cardservices@emp-group.com', 1, '6) AAIB Arab African International Bank >> Credit Emails 1/m', 210, 1);

-- RBGH – Regional Bank Ghana
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 0, 'RBGH', 'Regional Bank Ghana', 'RBGHCR', 0, 'HTML_RBGH', 0, 0, 0, 'CR', NULL, 'cardservices@emp-group.com', 1, 'RBGH Regional Bank Ghana >> Credit Emails 1/m', 215, 1);

-- ── RawData formatters ─────────────────────────────────────────────────────────

-- AIBK – Arab International Bank (branch 127) Raw Data Credit
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 127, 'AIBK', 'Arab International Bank', 'AIBKCR', 1, 'RAWDATA_AIBK', 256, 0, 0, 'CR', NULL, 'cardservices@emp-group.com', 1, '127) AIBK Arab Investment Bank >> Credit Raw Text 1/m', 300, 1);

-- EGB – Egyptian Gulf Bank (branch 128)
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 128, 'EGB', 'Egyptian Gulf Bank', 'EGBCR', 1, 'RAWDATA_EGB', 512, 0, 0, 'CR', NULL, 'cardservices@emp-group.com', 30, '128) EGB Egyptian Gulf Bank >> Credit OMR Raw Text 30/m', 310, 1);

-- AAIB – Arab African International Bank RawData (with overdue days)
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, FIELD_SEPARATOR, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 6, 'AAIB', 'Arab African International Bank', 'AAIBCR', 1, 'RAWDATA_AAIB', 64, 0, 0, 'CR', NULL, 'cardservices@emp-group.com', '|', 1, '6) AAIB Arab African International Bank >> Credit Raw Pipe 1/m', 315, 1);

-- ALXB – Alexandria Bank RawData
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 74, 'ALXB', 'Alexandria Bank', 'ALXBCR', 1, 'RAWDATA_ALXB', 128, 0, 0, 'CR', NULL, 'cardservices@emp-group.com', 1, '74) ALXB Alexandria Bank >> Credit Raw CSV 1/m', 320, 1);

-- ALXB Corporate RawData
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, USE_CORP_ACCT_NO, FIELD_SEPARATOR, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 74, 'ALXB', 'Alexandria Bank', 'ALXBCORP', 1, 'RAWDATA_ALXB_CORP', 130, 0, 0, 'CORP', NULL, 'cardservices@emp-group.com', 1, '|', 1, '74) ALXB Alexandria Bank Corporate >> Raw Pipe 1/m', 325, 1);

-- BRKA – Al Baraka Bank Egypt (branch 153)
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, FIELD_SEPARATOR, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 153, 'BRKA', 'Al Baraka Bank of Egypt', 'BRKACR', 1, 'RAWDATA_BRKA', 1, '''New Reward Contract''', 'cardservices@emp-group.com', '|', 30, '153) BRKA Al Baraka Bank of Egypt >> Credit Raw Pipe 30/m', 330, 1);

-- UNB RawData
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, FIELD_SEPARATOR, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 0, 'UNB', 'Union National Bank', 'UNBCR', 1, 'RAWDATA_UNB', 0, 0, 0, 'CR', NULL, 'cardservices@emp-group.com', '|', 1, 'UNB Union National Bank >> Credit Raw Pipe 1/m', 335, 1);

-- VCBK – Victoria Commercial Bank Kenya (branch 102)
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, FIELD_SEPARATOR, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 102, 'VCBK', 'Victoria Commercial Bank Ltd Kenya', 'VCBKCR', 1, 'RAWDATA_VCBK', 0, 0, 0, 'CR', NULL, 'cardservices@emp-group.com', '|', 1, '102) VCBK Victoria Commercial Bank Ltd Kenya >> Raw Text 1/m', 340, 1);

-- ── Text Label formatters ──────────────────────────────────────────────────────

-- FCMB – First City Monument Bank Nigeria (branch 73)
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, MAX_TRANS_PER_PAGE, MAX_TRANS_LAST_PAGE, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 73, 'FCMB', 'First City Monument Bank Nigeria', 'FCMBCR', 2, 'TEXTLABEL_FCMB', 1, 0, 0, 'CR', '''New Reward Contract''', 'cardservices@emp-group.com', 20, 27, 7, '73) FCMB First City Monument Bank Nigeria >> Default Credit Text 7/m', 400, 1);

-- Suez Canal Bank (branch 23)
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 23, 'SCB', 'Suez Canal Bank', 'SCBCR', 2, 'TEXTLABEL_SUEZ', 0, 0, 0, 'CR', NULL, 'cardservices@emp-group.com', 1, '23) SCB Suez Canal Bank >> Credit Text 1/m', 410, 1);

-- FBN Debit Text Label (branch 69)
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 69, 'FBN', 'First Bank of Nigeria', 'FBNDB_LBL', 2, 'TEXTLABEL_FBN_DB', 0, 1, 0, 'DB', NULL, 'cardservices@emp-group.com', 16, '69) FBN First Bank of Nigeria >> Debit Text Label 16/m', 420, 1);

-- AIB Debit Text Label (branch 5)
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 5, 'AIB', 'Arab International Bank', 'AIBDB_LBL', 2, 'TEXTLABEL_AIB_DB', 0, 1, 0, 'DB', NULL, 'cardservices@emp-group.com', 1, '5) AIB Arab International Bank >> Debit Text Label 1/m', 430, 1);

-- ICBG Debit Text Label (branch 50)
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 50, 'ICBG', 'Intercontinental Bank Ghana', 'ICBGDB_LBL', 2, 'TEXTLABEL_ICBG_DB', 0, 1, 0, 'DB', NULL, 'cardservices@emp-group.com', 1, '50) ICBG Intercontinental Bank Ghana >> Debit Text Label 1/m', 440, 1);

-- EDBE – Export Development Bank of Egypt Text Label (branch 76)
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 76, 'EDBE', 'Export Development Bank of Egypt', 'EDBECR', 2, 'TEXTLABEL_EDBE', 0, 0, 0, 'CR', NULL, 'cardservices@emp-group.com', 1, '76) EDBE Export Development Bank of Egypt >> Credit Text Label 1/m', 450, 1);

-- FABG – First Atlantic Bank Ghana Text Label
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 94, 'FABG', 'First Atlantic Bank Ghana', 'FABGCR', 2, 'TEXTLABEL_FABG', 0, 0, 0, 'CR', NULL, 'cardservices@emp-group.com', 1, '94) FABG First Atlantic Bank Ghana >> Credit Text Label 1/m', 460, 1);

-- ── Plain Text formatter ───────────────────────────────────────────────────────

-- EDBE plain text (branch 76)
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 76, 'EDBE', 'Export Development Bank of Egypt', 'EDBECR_TXT', 3, 'TEXT_EDBE', 0, 0, 0, 'CR', NULL, 'cardservices@emp-group.com', 1, '76) EDBE Export Development Bank of Egypt >> Credit Plain Text 1/m', 470, 1);

-- ── XML formatter ─────────────────────────────────────────────────────────────

-- IDBE – VIP XML (branch 16)
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 16, 'IDBE', 'Industrial Development Bank Egypt', 'IDBEVIP', 4, 'XML_IDBE', 8, 0, 0, 'VIP', NULL, 'cardservices@emp-group.com', 1, '16) IDBE Industrial Development Bank Egypt >> VIP XML 1/m', 500, 1);

-- ── PDF formatters ────────────────────────────────────────────────────────────

-- QNB (PDF rendered as structured HTML)
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 1, 'QNB', 'QNB Alahli', 'QNBCR', 5, 'PDF_QNB', 0, 0, 0, 'CR', NULL, 'cardservices@emp-group.com', 1, '[1] QNB ALAHLI Credit >> Classic Email 1/m', 600, 1);

-- BDCA PDF
INSERT INTO STAT_BANK_PRODUCT_CONFIG (ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT, OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES, CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX, REWARD_CONTRACT_COND, EMAIL_FROM_ADDRESS, SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE)
VALUES (STAT_BPCFG_SEQ.NEXTVAL, 41, 'BDCA', 'Banque Du Caire', 'BDCACR_PDF', 5, 'PDF_BDCA', 0, 0, 0, 'CR', NULL, 'cardservices@emp-group.com', 5, '41) BDCA Banque Du Caire >> Credit PDF 5/m', 610, 1);

COMMIT;

-- =============================================================================
-- Verify
-- =============================================================================
SELECT ID, BRANCH_CODE, BANK_NAME, FORMATTER_KEY, OUTPUT_TYPE, IS_ACTIVE
FROM   STAT_BANK_PRODUCT_CONFIG
ORDER  BY SORT_ORDER;
