-- =============================================================================
-- StatementFile src3 – Oracle DDL
-- =============================================================================
-- Creates the two tables that replace the 500-case switch statement in
-- frmStatementFileExtn.runStatement():
--
--   STAT_BANK_PRODUCT_CONFIG  – one row per bank/product combination
--   STAT_STATEMENT_RUN        – audit trail of each generation attempt
-- =============================================================================

-- ---------------------------------------------------------------------------
-- STAT_BANK_PRODUCT_CONFIG
-- ---------------------------------------------------------------------------
CREATE TABLE STAT_BANK_PRODUCT_CONFIG
(
    ID                        NUMBER(10)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IS_ACTIVE                 NUMBER(1)       DEFAULT 1 NOT NULL,

    -- Bank identification
    BANK_NAME                 VARCHAR2(50)    NOT NULL,
    BANK_FULL_NAME            VARCHAR2(200),
    BANK_CODE                 VARCHAR2(20),
    BRANCH_CODE               NUMBER(10)      NOT NULL,

    -- Product / statement type
    STATEMENT_TYPE_SUFFIX     VARCHAR2(20),   -- "CR","DB","CP","CRCORP","DBREWARD" …
    CARD_TYPE                 NUMBER(1)       NOT NULL,  -- 1=Credit 2=Debit 3=Corporate
    CARD_PRODUCT              VARCHAR2(100),
    OUTPUT_TYPE               NUMBER(1)       NOT NULL,  -- 1=Html 2=Pdf 3=Text 4=Raw 5=Xml 6=Email
    FORMATTER_KEY             VARCHAR2(100)   NOT NULL,  -- e.g. "HTML_UBA", "TXT_NSGB"

    -- Branding
    BANK_WEB_LINK             VARCHAR2(500),
    BANK_LOGO                 VARCHAR2(500),
    BACKGROUND_IMAGE          VARCHAR2(500),
    MID_BANNER_IMAGE          VARCHAR2(500),
    BOTTOM_BANNER_IMAGE       VARCHAR2(500),

    -- Email
    EMAIL_FROM_ADDRESS        VARCHAR2(200),
    EMAIL_FROM_NAME           VARCHAR2(200),

    -- Oracle query filters (SQL fragments)
    WHERE_CONDITION           VARCHAR2(2000),
    VIP_CONDITION             VARCHAR2(2000),
    REWARD_CONDITION          VARCHAR2(2000),
    REWARD_CONTRACT_CONDITION VARCHAR2(2000)  DEFAULT '''New Reward Contract''',
    CURRENCY_FILTER           VARCHAR2(2000),
    INSTALLMENT_CONDITION     VARCHAR2(2000),
    PAYMENT_SYSTEM            VARCHAR2(50),

    -- Processing flags
    PROCESSING_MODES          NUMBER(20)      DEFAULT 0,
    IS_REWARD_RUN             NUMBER(1)       DEFAULT 0,
    IS_SPLIT_OUTPUT           NUMBER(1)       DEFAULT 0,
    HAS_ATTACHMENT            NUMBER(1)       DEFAULT 0,
    SAVE_DATASET              NUMBER(1)       DEFAULT 0,
    SHOW_MESSAGE_BOX          NUMBER(1)       DEFAULT 0,
    RUN_NULL_CARD_DELETE      NUMBER(1)       DEFAULT 1,
    RUN_CARD_BRANCH_MATCH     NUMBER(1)       DEFAULT 1,
    EXCLUDE_REWARD            NUMBER(1)       DEFAULT 1,
    WAIT_PERIOD_SECONDS       NUMBER(5)       DEFAULT 0,

    -- Metadata
    CREATED_AT                TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATED_AT                TIMESTAMP       DEFAULT SYSTIMESTAMP
);

COMMENT ON TABLE  STAT_BANK_PRODUCT_CONFIG IS
    'Database-driven replacement for the 500-case switch in frmStatementFileExtn.runStatement(). '
    'Each row defines one bank/product statement run configuration.';

COMMENT ON COLUMN STAT_BANK_PRODUCT_CONFIG.FORMATTER_KEY IS
    'Registry key that maps to a concrete IStatementFormatter implementation. '
    'Convention: {OUTPUT_TYPE}_{BANK_MNEMONIC}, e.g. HTML_UBA, PDF_BDCA, TXT_NSGB.';

COMMENT ON COLUMN STAT_BANK_PRODUCT_CONFIG.PROCESSING_MODES IS
    'Bitfield of ProcessingMode enum flags: '
    '1=Installment, 2=FixArabicAddress, 4=FixAddress, 8=FixArabicAddressLang, '
    '16=DeleteOnHold, 32=Reward, 64=MergeMarkUpFees.';

-- ---------------------------------------------------------------------------
-- STAT_STATEMENT_RUN  – audit log
-- ---------------------------------------------------------------------------
CREATE TABLE STAT_STATEMENT_RUN
(
    ID                NUMBER(10)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CONFIG_ID         NUMBER(10)   NOT NULL REFERENCES STAT_BANK_PRODUCT_CONFIG(ID),
    STATEMENT_DATE    DATE         NOT NULL,
    STARTED_AT        TIMESTAMP    DEFAULT SYSTIMESTAMP,
    FINISHED_AT       TIMESTAMP,
    IS_SUCCESS        NUMBER(1)    DEFAULT 0,
    ERROR_MESSAGE     VARCHAR2(4000),
    FILES_GENERATED   NUMBER(10)   DEFAULT 0,
    EMAILS_SENT       NUMBER(10)   DEFAULT 0,
    STATEMENTS_COUNT  NUMBER(10)   DEFAULT 0,
    OUTPUT_DIRECTORY  VARCHAR2(1000)
);

COMMENT ON TABLE STAT_STATEMENT_RUN IS
    'Audit trail: one row written per statement generation attempt.';

-- ---------------------------------------------------------------------------
-- Sample data: seed a minimal UBA HTML configuration to replace case 5
-- ---------------------------------------------------------------------------
INSERT INTO STAT_BANK_PRODUCT_CONFIG (
    BANK_NAME, BANK_FULL_NAME, BANK_CODE, BRANCH_CODE,
    STATEMENT_TYPE_SUFFIX, CARD_TYPE, CARD_PRODUCT,
    OUTPUT_TYPE, FORMATTER_KEY,
    EMAIL_FROM_ADDRESS, EMAIL_FROM_NAME,
    RUN_NULL_CARD_DELETE, RUN_CARD_BRANCH_MATCH, EXCLUDE_REWARD
) VALUES (
    'UBA', 'United Bank for Africa', 'UBA01', 1,
    'CR', 1, 'UBA Credit Card',
    1, 'HTML_UBA',
    'cardservices@emp-group.com', 'UBA Card Services',
    1, 1, 1
);

COMMIT;
