using System;
using System.Collections.Generic;
using System.Data;
using Oracle.ManagedDataAccess.Client;
using StatementFile.Domain.Entities;
using StatementFile.Domain.Enums;
using StatementFile.Domain.Interfaces.Repositories;
using StatementFile.Infrastructure.Data;

namespace StatementFile.Infrastructure.Data.Repositories
{
    /// <summary>
    /// Oracle implementation of <see cref="IBankProductConfigRepository"/>.
    ///
    /// Reads/writes the STAT_BANK_PRODUCT_CONFIG table, which replaces the
    /// hundreds of hardcoded bank entries previously in frmStatementFileExtn.cs.
    ///
    /// All mutable fields of <see cref="BankProductConfig"/> are persisted.
    /// The primary key is generated by the Oracle sequence STAT_BPCFG_SEQ.
    /// </summary>
    public sealed class BankProductConfigRepository : IBankProductConfigRepository
    {
        private readonly OracleConnectionFactory _connFactory;

        public BankProductConfigRepository(OracleConnectionFactory connFactory)
        {
            _connFactory = connFactory ?? throw new ArgumentNullException(nameof(connFactory));
        }

        // ── SELECT helpers ────────────────────────────────────────────────────────

        private const string SelectColumns = @"
            ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT,
            OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES,
            CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX,
            REWARD_CONTRACT_COND, INSTALLMENT_CONTRACT_COND,
            APPEND_MODE, USE_CORP_ACCT_NO,
            REPORT_TEMPLATE_NAME, PDF_PASSWORD_SCHEME,
            EMAIL_FROM_ADDRESS, BANK_WEBSITE_URL,
            FACEBOOK_URL, LINKEDIN_URL, YOUTUBE_URL,
            MAX_TRANS_PER_PAGE, MAX_TRANS_LAST_PAGE,
            EMAIL_WAIT_MS, FIELD_SEPARATOR,
            SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE,
            CREATED_AT, MODIFIED_AT";

        private const string TableName = "STAT_BANK_PRODUCT_CONFIG";

        public IReadOnlyList<BankProductConfig> GetAll()
        {
            var list = new List<BankProductConfig>();
            using var conn = _connFactory.CreateOpenConnection();
            using var cmd  = new OracleCommand(
                $"SELECT {SelectColumns} FROM {TableName} ORDER BY SORT_ORDER, BRANCH_CODE", conn);
            using var rdr  = cmd.ExecuteReader();
            while (rdr.Read())
                list.Add(Map(rdr));
            return list;
        }

        public IReadOnlyList<BankProductConfig> GetActive()
        {
            var list = new List<BankProductConfig>();
            using var conn = _connFactory.CreateOpenConnection();
            using var cmd  = new OracleCommand(
                $"SELECT {SelectColumns} FROM {TableName} WHERE IS_ACTIVE = 1 ORDER BY SORT_ORDER, BRANCH_CODE", conn);
            using var rdr  = cmd.ExecuteReader();
            while (rdr.Read())
                list.Add(Map(rdr));
            return list;
        }

        public BankProductConfig GetById(int id)
        {
            using var conn = _connFactory.CreateOpenConnection();
            using var cmd  = new OracleCommand(
                $"SELECT {SelectColumns} FROM {TableName} WHERE ID = :id", conn);
            cmd.Parameters.Add(new OracleParameter(":id", OracleDbType.Int32) { Value = id });
            using var rdr  = cmd.ExecuteReader();
            return rdr.Read() ? Map(rdr) : null;
        }

        public int Insert(BankProductConfig config)
        {
            using var conn = _connFactory.CreateOpenConnection();
            using var cmd  = new OracleCommand(@"
                INSERT INTO STAT_BANK_PRODUCT_CONFIG (
                    ID, BRANCH_CODE, BANK_NAME, BANK_FULL_NAME, CARD_PRODUCT,
                    OUTPUT_TYPE, FORMATTER_KEY, PROCESSING_MODES,
                    CARD_TYPE, STATEMENT_TYPE, STATEMENT_TYPE_SUFFIX,
                    REWARD_CONTRACT_COND, INSTALLMENT_CONTRACT_COND,
                    APPEND_MODE, USE_CORP_ACCT_NO,
                    REPORT_TEMPLATE_NAME, PDF_PASSWORD_SCHEME,
                    EMAIL_FROM_ADDRESS, BANK_WEBSITE_URL,
                    FACEBOOK_URL, LINKEDIN_URL, YOUTUBE_URL,
                    MAX_TRANS_PER_PAGE, MAX_TRANS_LAST_PAGE,
                    EMAIL_WAIT_MS, FIELD_SEPARATOR,
                    SCHEDULED_DAY, DISPLAY_NAME, SORT_ORDER, IS_ACTIVE,
                    CREATED_AT, MODIFIED_AT
                ) VALUES (
                    STAT_BPCFG_SEQ.NEXTVAL,
                    :branchCode, :bankName, :bankFullName, :cardProduct,
                    :outputType, :formatterKey, :processingModes,
                    :cardType, :statementType, :stmtTypeSuffix,
                    :rewardCond, :installmentCond,
                    :appendMode, :useCorpAcct,
                    :reportTemplate, :pdfPwdScheme,
                    :emailFrom, :bankWebsite,
                    :facebookUrl, :linkedInUrl, :youTubeUrl,
                    :maxTransPage, :maxTransLast,
                    :emailWaitMs, :fieldSep,
                    :scheduledDay, :displayName, :sortOrder, :isActive,
                    :createdAt, :modifiedAt
                ) RETURNING ID INTO :newId", conn);

            AddWriteParams(cmd, config);
            var newId = new OracleParameter(":newId", OracleDbType.Int32)
                { Direction = ParameterDirection.Output };
            cmd.Parameters.Add(newId);

            cmd.ExecuteNonQuery();
            return Convert.ToInt32(newId.Value.ToString());
        }

        public void Update(BankProductConfig config)
        {
            using var conn = _connFactory.CreateOpenConnection();
            using var cmd  = new OracleCommand(@"
                UPDATE STAT_BANK_PRODUCT_CONFIG SET
                    BANK_FULL_NAME            = :bankFullName,
                    CARD_PRODUCT              = :cardProduct,
                    OUTPUT_TYPE               = :outputType,
                    FORMATTER_KEY             = :formatterKey,
                    PROCESSING_MODES          = :processingModes,
                    CARD_TYPE                 = :cardType,
                    STATEMENT_TYPE            = :statementType,
                    STATEMENT_TYPE_SUFFIX     = :stmtTypeSuffix,
                    REWARD_CONTRACT_COND      = :rewardCond,
                    INSTALLMENT_CONTRACT_COND = :installmentCond,
                    APPEND_MODE               = :appendMode,
                    USE_CORP_ACCT_NO          = :useCorpAcct,
                    REPORT_TEMPLATE_NAME      = :reportTemplate,
                    PDF_PASSWORD_SCHEME       = :pdfPwdScheme,
                    EMAIL_FROM_ADDRESS        = :emailFrom,
                    BANK_WEBSITE_URL          = :bankWebsite,
                    FACEBOOK_URL              = :facebookUrl,
                    LINKEDIN_URL              = :linkedInUrl,
                    YOUTUBE_URL               = :youTubeUrl,
                    MAX_TRANS_PER_PAGE        = :maxTransPage,
                    MAX_TRANS_LAST_PAGE       = :maxTransLast,
                    EMAIL_WAIT_MS             = :emailWaitMs,
                    FIELD_SEPARATOR           = :fieldSep,
                    SCHEDULED_DAY             = :scheduledDay,
                    DISPLAY_NAME              = :displayName,
                    SORT_ORDER                = :sortOrder,
                    IS_ACTIVE                 = :isActive,
                    MODIFIED_AT               = :modifiedAt
                WHERE ID = :id", conn);

            cmd.Parameters.Add(new OracleParameter(":bankFullName",   OracleDbType.Varchar2)  { Value = config.BankFullName });
            cmd.Parameters.Add(new OracleParameter(":cardProduct",    OracleDbType.Varchar2)  { Value = NullIfEmpty(config.CardProduct) });
            cmd.Parameters.Add(new OracleParameter(":outputType",     OracleDbType.Int32)     { Value = (int)config.OutputType });
            cmd.Parameters.Add(new OracleParameter(":formatterKey",   OracleDbType.Varchar2)  { Value = config.FormatterKey });
            cmd.Parameters.Add(new OracleParameter(":processingModes",OracleDbType.Int64)     { Value = (long)config.ProcessingModes });
            cmd.Parameters.Add(new OracleParameter(":cardType",       OracleDbType.Int32)     { Value = (int)config.CardType });
            cmd.Parameters.Add(new OracleParameter(":statementType",  OracleDbType.Int32)     { Value = (int)config.StatementType });
            cmd.Parameters.Add(new OracleParameter(":stmtTypeSuffix", OracleDbType.Varchar2)  { Value = config.StatementTypeSuffix });
            cmd.Parameters.Add(new OracleParameter(":rewardCond",     OracleDbType.Varchar2)  { Value = NullIfEmpty(config.RewardContractCondition) });
            cmd.Parameters.Add(new OracleParameter(":installmentCond",OracleDbType.Varchar2)  { Value = NullIfEmpty(config.InstallmentContractCondition) });
            cmd.Parameters.Add(new OracleParameter(":appendMode",     OracleDbType.Int32)     { Value = config.AppendMode ? 1 : 0 });
            cmd.Parameters.Add(new OracleParameter(":useCorpAcct",    OracleDbType.Int32)     { Value = config.UseCorporateAccountNumber ? 1 : 0 });
            cmd.Parameters.Add(new OracleParameter(":reportTemplate", OracleDbType.Varchar2)  { Value = NullIfEmpty(config.ReportTemplateName) });
            cmd.Parameters.Add(new OracleParameter(":pdfPwdScheme",   OracleDbType.Varchar2)  { Value = NullIfEmpty(config.PdfPasswordScheme) });
            cmd.Parameters.Add(new OracleParameter(":emailFrom",      OracleDbType.Varchar2)  { Value = config.EmailFromAddress });
            cmd.Parameters.Add(new OracleParameter(":bankWebsite",    OracleDbType.Varchar2)  { Value = NullIfEmpty(config.BankWebsiteUrl) });
            cmd.Parameters.Add(new OracleParameter(":facebookUrl",    OracleDbType.Varchar2)  { Value = NullIfEmpty(config.FacebookUrl) });
            cmd.Parameters.Add(new OracleParameter(":linkedInUrl",    OracleDbType.Varchar2)  { Value = NullIfEmpty(config.LinkedInUrl) });
            cmd.Parameters.Add(new OracleParameter(":youTubeUrl",     OracleDbType.Varchar2)  { Value = NullIfEmpty(config.YouTubeUrl) });
            cmd.Parameters.Add(new OracleParameter(":maxTransPage",   OracleDbType.Int32)     { Value = config.MaxTransactionsPerPage });
            cmd.Parameters.Add(new OracleParameter(":maxTransLast",   OracleDbType.Int32)     { Value = config.MaxTransactionsLastPage });
            cmd.Parameters.Add(new OracleParameter(":emailWaitMs",    OracleDbType.Int32)     { Value = config.EmailWaitPeriodMs });
            cmd.Parameters.Add(new OracleParameter(":fieldSep",       OracleDbType.Varchar2)  { Value = config.FieldSeparator });
            cmd.Parameters.Add(new OracleParameter(":scheduledDay",   OracleDbType.Int32)     { Value = config.ScheduledDay });
            cmd.Parameters.Add(new OracleParameter(":displayName",    OracleDbType.Varchar2)  { Value = NullIfEmpty(config.DisplayName) });
            cmd.Parameters.Add(new OracleParameter(":sortOrder",      OracleDbType.Int32)     { Value = config.SortOrder });
            cmd.Parameters.Add(new OracleParameter(":isActive",       OracleDbType.Int32)     { Value = config.IsActive ? 1 : 0 });
            cmd.Parameters.Add(new OracleParameter(":modifiedAt",     OracleDbType.TimeStamp) { Value = config.ModifiedAt });
            cmd.Parameters.Add(new OracleParameter(":id",             OracleDbType.Int32)     { Value = config.Id });

            cmd.ExecuteNonQuery();
        }

        public void Delete(int id)
        {
            using var conn = _connFactory.CreateOpenConnection();
            using var cmd  = new OracleCommand(
                "DELETE FROM STAT_BANK_PRODUCT_CONFIG WHERE ID = :id", conn);
            cmd.Parameters.Add(new OracleParameter(":id", OracleDbType.Int32) { Value = id });
            cmd.ExecuteNonQuery();
        }

        // ── Private helpers ───────────────────────────────────────────────────────

        private static void AddWriteParams(OracleCommand cmd, BankProductConfig config)
        {
            cmd.Parameters.Add(new OracleParameter(":branchCode",     OracleDbType.Int32)     { Value = config.BranchCode });
            cmd.Parameters.Add(new OracleParameter(":bankName",       OracleDbType.Varchar2)  { Value = config.BankName });
            cmd.Parameters.Add(new OracleParameter(":bankFullName",   OracleDbType.Varchar2)  { Value = config.BankFullName });
            cmd.Parameters.Add(new OracleParameter(":cardProduct",    OracleDbType.Varchar2)  { Value = NullIfEmpty(config.CardProduct) });
            cmd.Parameters.Add(new OracleParameter(":outputType",     OracleDbType.Int32)     { Value = (int)config.OutputType });
            cmd.Parameters.Add(new OracleParameter(":formatterKey",   OracleDbType.Varchar2)  { Value = config.FormatterKey });
            cmd.Parameters.Add(new OracleParameter(":processingModes",OracleDbType.Int64)     { Value = (long)config.ProcessingModes });
            cmd.Parameters.Add(new OracleParameter(":cardType",       OracleDbType.Int32)     { Value = (int)config.CardType });
            cmd.Parameters.Add(new OracleParameter(":statementType",  OracleDbType.Int32)     { Value = (int)config.StatementType });
            cmd.Parameters.Add(new OracleParameter(":stmtTypeSuffix", OracleDbType.Varchar2)  { Value = config.StatementTypeSuffix });
            cmd.Parameters.Add(new OracleParameter(":rewardCond",     OracleDbType.Varchar2)  { Value = NullIfEmpty(config.RewardContractCondition) });
            cmd.Parameters.Add(new OracleParameter(":installmentCond",OracleDbType.Varchar2)  { Value = NullIfEmpty(config.InstallmentContractCondition) });
            cmd.Parameters.Add(new OracleParameter(":appendMode",     OracleDbType.Int32)     { Value = config.AppendMode ? 1 : 0 });
            cmd.Parameters.Add(new OracleParameter(":useCorpAcct",    OracleDbType.Int32)     { Value = config.UseCorporateAccountNumber ? 1 : 0 });
            cmd.Parameters.Add(new OracleParameter(":reportTemplate", OracleDbType.Varchar2)  { Value = NullIfEmpty(config.ReportTemplateName) });
            cmd.Parameters.Add(new OracleParameter(":pdfPwdScheme",   OracleDbType.Varchar2)  { Value = NullIfEmpty(config.PdfPasswordScheme) });
            cmd.Parameters.Add(new OracleParameter(":emailFrom",      OracleDbType.Varchar2)  { Value = config.EmailFromAddress });
            cmd.Parameters.Add(new OracleParameter(":bankWebsite",    OracleDbType.Varchar2)  { Value = NullIfEmpty(config.BankWebsiteUrl) });
            cmd.Parameters.Add(new OracleParameter(":facebookUrl",    OracleDbType.Varchar2)  { Value = NullIfEmpty(config.FacebookUrl) });
            cmd.Parameters.Add(new OracleParameter(":linkedInUrl",    OracleDbType.Varchar2)  { Value = NullIfEmpty(config.LinkedInUrl) });
            cmd.Parameters.Add(new OracleParameter(":youTubeUrl",     OracleDbType.Varchar2)  { Value = NullIfEmpty(config.YouTubeUrl) });
            cmd.Parameters.Add(new OracleParameter(":maxTransPage",   OracleDbType.Int32)     { Value = config.MaxTransactionsPerPage });
            cmd.Parameters.Add(new OracleParameter(":maxTransLast",   OracleDbType.Int32)     { Value = config.MaxTransactionsLastPage });
            cmd.Parameters.Add(new OracleParameter(":emailWaitMs",    OracleDbType.Int32)     { Value = config.EmailWaitPeriodMs });
            cmd.Parameters.Add(new OracleParameter(":fieldSep",       OracleDbType.Varchar2)  { Value = config.FieldSeparator });
            cmd.Parameters.Add(new OracleParameter(":scheduledDay",   OracleDbType.Int32)     { Value = config.ScheduledDay });
            cmd.Parameters.Add(new OracleParameter(":displayName",    OracleDbType.Varchar2)  { Value = NullIfEmpty(config.DisplayName) });
            cmd.Parameters.Add(new OracleParameter(":sortOrder",      OracleDbType.Int32)     { Value = config.SortOrder });
            cmd.Parameters.Add(new OracleParameter(":isActive",       OracleDbType.Int32)     { Value = config.IsActive ? 1 : 0 });
            cmd.Parameters.Add(new OracleParameter(":createdAt",      OracleDbType.TimeStamp) { Value = config.CreatedAt });
            cmd.Parameters.Add(new OracleParameter(":modifiedAt",     OracleDbType.TimeStamp) { Value = config.ModifiedAt });
        }

        private static BankProductConfig Map(IDataReader r)
        {
            int id = r.GetInt32(0);

            var config = BankProductConfig.Create(
                branchCode:                  r.GetInt32(1),
                bankName:                    r.IsDBNull(2)  ? string.Empty : r.GetString(2),
                bankFullName:                r.IsDBNull(3)  ? string.Empty : r.GetString(3),
                cardProduct:                 r.IsDBNull(4)  ? string.Empty : r.GetString(4),
                outputType:                  (StatementOutputType)r.GetInt32(5),
                formatterKey:                r.IsDBNull(6)  ? string.Empty : r.GetString(6),
                processingModes:             (ProcessingMode)r.GetInt64(7),
                cardType:                    (CardType)r.GetInt32(8),
                statementType:               (StatementType)r.GetInt32(9),
                statementTypeSuffix:         r.IsDBNull(10) ? "CR"          : r.GetString(10),
                rewardContractCondition:     r.IsDBNull(11) ? null           : r.GetString(11),
                installmentContractCondition:r.IsDBNull(12) ? null           : r.GetString(12),
                appendMode:                  r.GetInt32(13) == 1,
                useCorporateAccountNumber:   r.GetInt32(14) == 1,
                reportTemplateName:          r.IsDBNull(15) ? null           : r.GetString(15),
                pdfPasswordScheme:           r.IsDBNull(16) ? null           : r.GetString(16),
                emailFromAddress:            r.IsDBNull(17) ? null           : r.GetString(17),
                bankWebsiteUrl:              r.IsDBNull(18) ? null           : r.GetString(18),
                facebookUrl:                 r.IsDBNull(19) ? null           : r.GetString(19),
                linkedInUrl:                 r.IsDBNull(20) ? null           : r.GetString(20),
                youTubeUrl:                  r.IsDBNull(21) ? null           : r.GetString(21),
                maxTransactionsPerPage:      r.GetInt32(22),
                maxTransactionsLastPage:     r.GetInt32(23),
                emailWaitPeriodMs:           r.GetInt32(24),
                fieldSeparator:              r.IsDBNull(25) ? ","            : r.GetString(25),
                scheduledDay:                r.GetInt32(26),
                displayName:                 r.IsDBNull(27) ? null           : r.GetString(27),
                sortOrder:                   r.GetInt32(28),
                isActive:                    r.GetInt32(29) == 1);

            return BankProductConfig.Reconstitute(id, config);
        }

        private static object NullIfEmpty(string s)
            => string.IsNullOrEmpty(s) ? (object)DBNull.Value : s;
    }
}
