
({@F_branch} = 25 and {@f_closingbalance} <> 0 and {@f_contracttype} <> 'Reward Program (Airmile)') and
({@f_BranchTrans} = 25 and not IsNull({@f_POSTINGDATE}) and not IsNull({@f_DOCNO}) and {@f_TRANDESCRIPTION} <> 'Calculated Points') 



create or replace view v_statementmasterreward as
select "BRANCH","STATEMENTNO","STATEMENTNUMBER","STATEMENTDATEFROM","STATEMENTDATETO","STATEMENTTYPE","STATEMENTSENDTYPE","STETEMENTDUEDATE","STATEMENTMESSAGELINE1","STATEMENTMESSAGELINE2","STATEMENTMESSAGELINE3","CONTRACTNO","CONTRACTTYPE","CONTRACTCREATIONDATE","CONTRACTSTATUS","COMPANYCODE","REGISTRATIONNUMBER","CONTRACTLIMIT","CUSTOMERNO","CUSTOMERTITLE","CUSTOMERNAME","CUSTOMERCREATIONDATE","CUSTOMERTYPE","CUSTOMERSTATUS","CLIENTID","EMPLOYER","DEPT","POSITION","EMPLOYEENUMBER","CUSTOMERCOUNTRY","CUSTOMERREGION","CUSTOMERCITY","CUSTOMERZIPCODE","CUSTOMERADDRESS1","CUSTOMERADDRESS2","CUSTOMERADDRESS3","CUSTOMERADDRESSPARCODE","ACCOUNTNO","EXTERNALNO","ACCOUNTCREATIONDATE","ACCOUNTTYPE","ACCOUNTSTATUS","ACCOUNTCURRENCY","ACCOUNTCOUNTRY","ACCOUNTREGION","ACCOUNTCITY","ACCOUNTZIPCODE","ACCOUNTADDRESS1","ACCOUNTADDRESS2","ACCOUNTADDRESS3","ACCOUNTADDRESSPARCODE","ACCOUNTLIM","ACCOUNTAVAILABLELIM","ACCOUNTCASHLIM","ACCOUNTAVAILABLECASHLIM","CARDNO","MBR","CARDTYPE","CARDCREATIONDATE","CARDEXPIRYDATE","CARDLASTMODIFICATIONDATE","CARDPRODUCT","CARDSTATE","CARDSTATUS","CARDSTATUSDATE","CARDCURRENCY","CARDBIRTHDATE","CARDTITLE","CARDVIP","CARDPRIMARY","PRINARYCARDNO","CARDBRANCHPART","CARDBRANCHPARTNAME","CARDACCOUNTNO","CARDCLIENTNAME","CARDPAYMENTMETHOD","CARDLIMIT","CARDAVAILABLELIMIT","CARDCASHLIMIT","CARDAVAILABLECASHLIMIT","CARDCOUNTRY","CARDREGION","CARDCITY","CARDZIPCODE","CARDADDRESS1","CARDADDRESS2","CARDADDRESS3","CARDADDRESSBARCODE","TOTALDUEAMOUNT","MINDUEAMOUNT","OPENINGBALANCE","CLOSINGBALANCE","TOTALPURCHASES","TOTALCASHWITHDRAWAL","TOTALINTEREST","TOTALPAYMENTS","TOTALCHARGES","TOTALCREDITSANDREFUNDS","TOTALDEBITS","TOTALCREDITS","TOTALSUSPENDS","TOTALOVERDUEAMOUNT","TOTALOVERLIMITAMOUNT","HOLSTMT","BARCODE","USERACTFIELD1","USERACTFIELD2","USERCUSTFIELD1","USERCUSTFIELD2","USERCARDFIELD1","USERCARDFIELD2","EARNEDBONUS","REDEEMEDBONUS","EXPIREDBONUS","CREDITCONTRACTS" from tstatementmastertable x
where x.contracttype = 'Reward Program (Airmile)'




create or replace view v_statementdetailreward as
select "BRANCH","STATEMENTNO","STATEMENTNUMBER","CONTRACTNO","ACCOUNTNO","ACCOUNTCURRENCY","CARDNO","MBR","TRANSDATE","POSTINGDATE","TRANDESCRIPTION","MERCHANT","ORIGTRANAMOUNT","ORIGTRANCURRENCY","BILLTRANAMOUNT","BILLTRANAMOUNTSIGN","DOCNO","REFERENENO" from tstatementdetailtable x
where x.trandescription = 'Calculated Points'